# Generated by Django 4.2.7 on 2023-11-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
